path:  C:\Users\samar\Desktop\capstone\anprtest4\datasets # prefer abs path
train: train/images # train images (relative to 'path')
val: train/images  # val images (relative to 'path')

# Classes
names:
  0: license_plate